{
 "title": "Docker Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-490m", "to": "now-80m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'nodeexporter:9100',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'nodeexporter:9100',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'nodeexporter:9100',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'nodeexporter:9100',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes - node_filesystem_free_bytes)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Avaliable" }
   ]
  },
  {
   "title": "Available Volume Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\"}",
     "legendFormat": "{{device}}_Available"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"}",
     "legendFormat": "{{device}}_Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 2, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{device=\"/dev/root\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_filesystem_files{device=\"/dev/root\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"nodeexporter:9100\"} / (node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"nodeexporter:9100\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"nodeexporter:9100\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"} / node_memory_SwapTotal_bytes{instance=~\"nodeexporter:9100\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  }
 ]
}