{
 "title": "Docker Containers New",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"aufs\"} - node_filesystem_free_bytes{fstype=\"aufs\"}) / node_filesystem_size_bytes{fstype=\"aufs\"}  * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "Host CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Host Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Container Storage Size (MiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"avocetodsconsumer\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"avoceteventworker\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"avocet_cache\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"kafka\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"zookeeper\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"}[1m]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers CPU Utilisation %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"})",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image=\"avocetodsrepo.azurecr.io/avoceteventconsumer:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image=\"avocetodsrepo.azurecr.io/avoceteventworker:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image=\"avocetodsrepo.azurecr.io/kafkaalpine:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image=\"avocetodsrepo.azurecr.io/redisalpine:7.0.4\"}[1m]))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image=\"avocetodsrepo.azurecr.io/avocetodseventconsumer:latest\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  }
 ]
}